hailort_version: "4.20.0"
tappas_version: "3.31.0"
apps_infra_version: "25.3.1"
model_zoo_version: "2.14.0"
device_arch: "rpi5"
resource_path: "/usr/local/hailo/resources"
python_version: "3.11"
auto_symlink: true
